### ISSUE TITLE
Way to set the request on a POST and verify it

### ISSUE THREAD

**Issue by zachgoldstein** [nicholasf/fakepoint#3]

**Comment by zachgoldstein** [comment]
What do you think of adding some sort of `.SetRequest()` on `Fakepoint` so that when I do a post on the http.client, I can make sure the body of that matches what I expect?

**Comment by nicholasf** [comment]
Hrm, so you can assert that certain JSON fields are present in the post? That would definitely be something we could use.

Like, it might be that we’d set a way of testing the parameters of the request. Mark had an idea like this, where we’d set a function in there somehow.

```
func Tester(b request.Body) (err, error) { 

   //this would make assertions about whether the request Body held correct JSON, etc. 
}

maker.NewPost(“http://abc.com <http://abc.com/>”, 200).SetResponse(“ok”).SetTest(Tester)
```

This would be immediately useful for the stuff we do, wouldn’t it?

**Comment by zachgoldstein** [comment]
Ok so I think there's three ideas here:
- I want to check that the full body set in `.SetRequest` matches what I send in `client.Post()`
- I want to make sure my posts have a certain field & value. Could be a `.SetJSONField()` and then we convert the body set in `client.Post()` to JSON and search through to make sure it's there.
- I want to have my own func check the request. Could be a `.SetTest()` (I like calling it `.SetRequestTest()` better :) )

I was only referring to the first case, which is the most trivial. Love all of these though.

**Comment by zachgoldstein** [comment]
Maybe let's break this into three issues to tackle separately. The third one is probably the most useful. Totally agree that we could put that to use super quick.

**Comment by nicholasf** [comment]
Ok. Maybe wait until lunch tomorrow to talk about this before investing any work.

I like the general idea but the ‘SetRequest’ DSL doesn’t make sense to me. That’s what happens when you use `maker.NewGet`, etc.. The DSL wouldn’t build the request, or a json field, etc., it would just expose a way for the developer to execute a function against the request somewhere around here - https://github.com/nicholasf/fakepoint/blob/master/fakepoint.go#L76 https://github.com/nicholasf/fakepoint/blob/master/fakepoint.go#L76 .

Cheers,
Nick
