### ISSUE TITLE
introduce regex matching for URLs

### ISSUE THREAD

**Issue by nicholasf** [nicholasf/fakepoint#5]
This will take some thought:

```
2:15 PM <nicholasf> hrm .. I'm trying to work out a nice way of introducing regexes into a URL matching lib I wrote (fakepoint)
2:15 PM <nicholasf> so, right now you do something like this ...
New messages
2:15 PM <nicholasf> maker.NewGet("http://example.com", 200).SetResponse("")
2:16 PM <nicholasf> which is probably obvious
2:16 PM <nicholasf> next I want to to be able to do something like
2:16 PM <nicholasf> maker.NewGet("http://ex*.*", 200).SetResponse("") 
2:16 PM <nicholasf> for a naive regex pattern
2:17 PM <nicholasf> but I dont want to force the test writer to have to escape the forward slashes, the dots, etc, that are typical in a URL
2:19 PM <nicholasf> I suppose I could (a) create a new function - NewGetUsingRegex (or something) that took an explicit regexp, (b) or make everything after the http:// a regexp and perhaps introduce some delimiters so each section of the URL could become a regex - "http://{ex.*}.{.*om}" etc
2:19 PM <nicholasf> I guess (a) is easiest
```

**Comment by markmandel** [comment]
Vague Saturday thinking ;) Not entirely well formed yet.

I'm thinking the first argument is the base. From I was wondering if it was easier to just make `NewGet()` varardic, such that it can take a (or more?) functions that can be matched against the end path of the URL? 

Something like (return the 200 if it ends with ".go"):

``` go
maker.PlanGet("http://example.com", 200, func(path string) boolean {
   return strings.HasSuffix(".go")
}).SetResponse("")
```

Then that function could do regex matching, or suffix matching, etc.

You could also have common HOFs that do suffix/contains/prefix/regex in the libraries too.

This also feels a lot like what our Mr Cheney talks about here too: http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

...or you could extend the `Fakepont` object to have a `.Match(func(path string) bool)` function to extend the DSL - that could make more sense too.

So that becomes something like:

``` go
maker.PlanGet("http://example.com", 200,).Match(func(path string) boolean {
   return strings.HasSuffix(".go")
}).SetResponse("")
```

**Comment by nicholasf** [comment]
Hem, let's discuss this later. nock uses a similar approach of passing in functions and it ends up becoming too complex. Right now the simplicity works. 

Great. Article from @davecheney. I think, in this case, I might add a second function just for regexes. I'm already doing chained functions. I'd probably use variadic args if I wanted to replace those.
